import '../data/fashion_image_urls.dart';
import '../data/men_accessories_catalog_image_urls.dart';
import '../data/men_casual_wear_item_image_urls.dart';
import '../data/men_formal_wear_catalog_image_urls.dart';
import '../data/women_casual_wear_catalog_image_urls.dart';
import '../data/kids_boys_catalog_image_urls.dart';
import 'catalogue_extension.dart';
import 'sample_product_helpers.dart';

/// Full ATELIER catalogue — every department subcategory has products.
/// Inspired by NOLIMIT, ODEL & Sri Lankan department stores (LKR). Images via Pexels CDN.
final sampleProductDocs = <Map<String, dynamic>>[
  // ─── MEN · Casual Wear ───────────────────────────────────────────────────
  sampleProduct(
    id: 'nolimit-polo',
    name: 'Pique Polo Shirt',
    brand: 'NOLIMIT',
    categoryId: 'men',
    subCategoryId: 'casual-wear',
    price: 2490,
    photoId: FashionPhotos.poloNavy1,
    catalogImageUrl: MenCasualWearItemImageUrls.list[5], // Emerald grey polo hero
    retailerUrl: '$kNolimit/collections/mens',
    description: 'Classic pique polo — NOLIMIT bestseller for everyday casual.',
    isFeatured: true,
  ),
  sampleProduct(
    id: 'cotton-linen-shirt',
    name: 'Linen Blend Casual Shirt',
    brand: 'Cotton Collection',
    categoryId: 'men',
    subCategoryId: 'casual-wear',
    price: 4590,
    photoId: FashionPhotos.linenBeige1,
    catalogImageUrl: MenCasualWearItemImageUrls.list[0],
    retailerUrl: kCotton,
    isFeatured: true,
  ),
  sampleProduct(
    id: 'ekko-chino',
    name: 'Smart Stretch Chino',
    brand: 'Ekko',
    categoryId: 'men',
    subCategoryId: 'casual-wear',
    price: 3790,
    photoId: FashionPhotos.chinoKhaki1,
    catalogImageUrl: MenCasualWearItemImageUrls.casualBottomsHeroUrls[0], // light-wash denim hero
  ),
  sampleProduct(
    id: 'tfo-denim-jacket',
    name: 'Denim Trucker Jacket',
    brand: 'The Factory Outlet',
    categoryId: 'men',
    subCategoryId: 'casual-wear',
    price: 5490,
    photoId: FashionPhotos.denimIndigo1,
    catalogImageUrl: MenCasualWearItemImageUrls.casualBottomsHeroUrls[1], // dark denim hero
    isFeatured: true,
  ),
  sampleProduct(
    id: 'nolimit-cargo-shorts',
    name: 'Relaxed Cargo Shorts',
    brand: 'NOLIMIT',
    categoryId: 'men',
    subCategoryId: 'casual-wear',
    price: 2990,
    photoId: FashionPhotos.chinoNavy1,
    catalogImageUrl: MenCasualWearItemImageUrls.casualBottomsHeroUrls[2], // navy cargo shorts hero
    retailerUrl: kNolimit,
  ),

  sampleProduct(
    id: 'nolimit-slim-polo-forest',
    name: "Men's Slim Fit Polo T-Shirt Forest Green",
    brand: 'NOLIMIT',
    categoryId: 'men',
    subCategoryId: 'casual-wear',
    price: 2790,
    photoId: FashionPhotos.crewForest1,
    catalogImageUrl: MenCasualWearItemImageUrls.list[4],
    retailerUrl: '$kNolimit/collections/mens',
    description: 'Slim fit pique polo in forest green — NOLIMIT casual.',
  ),
  sampleProduct(
    id: 'tom-david-oversized-tee-navy',
    name: "Men's Oversized T-Shirt Navy",
    brand: 'TOM DAVID',
    categoryId: 'men',
    subCategoryId: 'casual-wear',
    price: 2990,
    photoId: FashionPhotos.poloNavy2,
    catalogImageUrl: MenCasualWearItemImageUrls.list[2],
    retailerUrl: kNolimit,
    description: 'Oversized tee with varsity graphic — navy.',
  ),
  sampleProduct(
    id: 'tom-david-oversized-tee-mint',
    name: "Men's Oversized T-Shirt Mint Green",
    brand: 'TOM DAVID',
    categoryId: 'men',
    subCategoryId: 'casual-wear',
    price: 2990,
    photoId: FashionPhotos.teeSand1,
    catalogImageUrl: MenCasualWearItemImageUrls.list[3],
    retailerUrl: kNolimit,
    description: 'Oversized tee with faded graphic — mint green.',
  ),
  // ─── MEN · Formal Wear ───────────────────────────────────────────────────
  sampleProduct(
    id: 'nolimit-formal-shirt',
    name: 'Slim Fit Formal Shirt',
    brand: 'NOLIMIT',
    categoryId: 'men',
    subCategoryId: 'formal-wear',
    price: 3990,
    photoId: FashionPhotos.shirtWhite1,
    catalogImageUrl: MenFormalWearCatalogImageUrls.list[0],
    retailerUrl: '$kNolimit/collections/men-shirts',
    isFeatured: true,
  ),
  sampleProduct(
    id: 'signature-blazer',
    name: 'Premium Tailored Blazer',
    brand: 'Signature',
    categoryId: 'men',
    subCategoryId: 'formal-wear',
    price: 14990,
    photoId: FashionPhotos.blazerNavy1,
    catalogImageUrl: MenFormalWearCatalogImageUrls.list[4],
    retailerUrl: kSignature,
    isFeatured: true,
  ),
  sampleProduct(
    id: 'fashionbug-formal-shirt-180dbl',
    name: "Men's Long Sleeve Formal Shirt",
    brand: 'Fashion Bug',
    categoryId: 'men',
    subCategoryId: 'formal-wear',
    price: 3890,
    photoId: FashionPhotos.shirtCharcoal1,
    catalogImageUrl: MenFormalWearCatalogImageUrls.list[1],
    retailerUrl: kFashionBug,
  ),
  sampleProduct(
    id: 'fashionbug-formal-shirt-092wt',
    name: "Men's Formal Shirt (White)",
    brand: 'Fashion Bug',
    categoryId: 'men',
    subCategoryId: 'formal-wear',
    price: 3690,
    photoId: FashionPhotos.shirtWhite1,
    catalogImageUrl: MenFormalWearCatalogImageUrls.list[2],
    retailerUrl: kFashionBug,
  ),
  sampleProduct(
    id: 'fashionbug-formal-shirt-089dbl',
    name: "Men's Slim Fit Formal Shirt",
    brand: 'Fashion Bug',
    categoryId: 'men',
    subCategoryId: 'formal-wear',
    price: 3690,
    photoId: FashionPhotos.shirtBlue1,
    catalogImageUrl: MenFormalWearCatalogImageUrls.list[3],
    retailerUrl: kFashionBug,
  ),

  // ─── MEN · Accessories ───────────────────────────────────────────────────
  sampleProduct(
    id: 'nolimit-fossil-grant-chrono-leather',
    name: 'Fossil Grant Chronograph Leather Watch',
    brand: 'FOSSIL',
    categoryId: 'men',
    subCategoryId: 'accessories',
    price: 27990,
    photoId: FashionPhotos.watchClose,
    catalogImageUrl: MenAccessoriesCatalogImageUrls.list[0],
    retailerUrl: kNolimit,
    description: 'Black dial, black leather strap — chronograph.',
    isFeatured: true,
  ),
  sampleProduct(
    id: 'nolimit-fossil-everett-chrono-steel',
    name: 'Fossil Everett Chronograph Stainless Steel Watch',
    brand: 'FOSSIL',
    categoryId: 'men',
    subCategoryId: 'accessories',
    price: 28990,
    photoId: FashionPhotos.watchClose,
    catalogImageUrl: MenAccessoriesCatalogImageUrls.list[1],
    retailerUrl: kNolimit,
    description: 'Stainless steel bracelet, chronograph.',
    isFeatured: true,
  ),
  sampleProduct(
    id: 'nolimit-deedat-hyper-slipper-black',
    name: 'DEEDAT Hyper Slipper (Black)',
    brand: 'DEEDAT',
    categoryId: 'men',
    subCategoryId: 'accessories',
    price: 2990,
    photoId: FashionPhotos.chinoNavy1,
    catalogImageUrl: MenAccessoriesCatalogImageUrls.list[2],
    retailerUrl: kNolimit,
    description: 'Casual thong slipper — black.',
  ),
  sampleProduct(
    id: 'nolimit-mbrk-invisible-socks-black',
    name: "Men's Invisible Length Socks (Black)",
    brand: 'NOLIMIT',
    categoryId: 'men',
    subCategoryId: 'accessories',
    price: 990,
    photoId: FashionPhotos.crewGrey1,
    catalogImageUrl: MenAccessoriesCatalogImageUrls.list[3],
    retailerUrl: kNolimit,
    description: 'MBRK invisible-length socks — black.',
  ),
  sampleProduct(
    id: 'nolimit-reversible-formal-belt-black',
    name: "Men's Reversible Synthetic Formal Belt (Black)",
    brand: 'NOLIMIT',
    categoryId: 'men',
    subCategoryId: 'accessories',
    price: 1990,
    photoId: FashionPhotos.watchClose,
    catalogImageUrl: MenAccessoriesCatalogImageUrls.list[4],
    retailerUrl: kNolimit,
    description: 'Reversible synthetic formal belt.',
  ),
  sampleProduct(
    id: 'nolimit-deedat-sports-shoe-white',
    name: "DEEDAT Men's Sports Shoe (White)",
    brand: 'DEEDAT',
    categoryId: 'men',
    subCategoryId: 'accessories',
    price: 12990,
    photoId: FashionPhotos.sportRun,
    catalogImageUrl: MenAccessoriesCatalogImageUrls.list[5],
    retailerUrl: kNolimit,
    description: 'White sports shoe — DEEDAT.',
  ),

  // ─── WOMEN · Casual Wear ─────────────────────────────────────────────────
  sampleProduct(
    id: 'nolimit-haj-modest-womens-printed-casual-dress-beige',
    name: "NOLIMIT HAJ MODEST Women's Printed Casual Dress (Beige)",
    brand: 'NOLIMIT HAJ MODEST',
    categoryId: 'women',
    subCategoryId: 'casual-wear',
    price: 7990,
    photoId: FashionPhotos.womanDress1,
    catalogImageUrl: WomenCasualWearCatalogImageUrls.list[0],
    retailerUrl: kNolimit,
    description: 'Modest printed casual dress — beige ground with floral sketch print.',
  ),
  sampleProduct(
    id: 'nolimit-modest-womens-shirt-collar-printed-casual-dress-navy',
    name: "NOLIMIT MODEST Women's Shirt Collar Printed Casual Dress (Navy)",
    brand: 'NOLIMIT MODEST',
    categoryId: 'women',
    subCategoryId: 'casual-wear',
    price: 8490,
    photoId: FashionPhotos.womanDress1,
    catalogImageUrl: 'assets/images/nolimit_modest_womens_shirt_collar_printed_casual_dress_navy.jpg',
    retailerUrl: kNolimit,
    description: 'Shirt-collar midi dress — navy & white ornate print, tie waist.',
  ),
  sampleProduct(
    id: 'deedat-womens-high-neck-tee-light-blue',
    name: "DEEDAT Women's High Neck T-Shirt (Light Blue)",
    brand: 'DEEDAT',
    categoryId: 'women',
    subCategoryId: 'casual-wear',
    price: 2990,
    photoId: FashionPhotos.womanCasual2,
    catalogImageUrl: 'assets/images/deedat_womens_high_neck_tee_light_blue.jpg',
    retailerUrl: kNolimit,
    description: 'Fine-gauge knit mock-neck tee — light blue, cropped silhouette.',
  ),
  sampleProduct(
    id: 'nolimit-offbeat-womens-shirt-collar-casual-blouse-dark-purple',
    name: "NOLIMIT OFFBEAT IMPRESSIONS Women's Shirt Collar Casual Blouse (Dark Purple)",
    brand: 'NOLIMIT OFFBEAT IMPRESSIONS',
    categoryId: 'women',
    subCategoryId: 'casual-wear',
    price: 3490,
    photoId: FashionPhotos.womanFormal3,
    catalogImageUrl: 'assets/images/nolimit_offbeat_womens_shirt_collar_blouse_dark_purple.jpg',
    retailerUrl: kNolimit,
    description: 'Satin-finish shirt collar blouse — dark purple, relaxed fit.',
  ),
  sampleProduct(
    id: 'nolimit-offbeat-womens-printed-embroidery-tee-cream',
    name: "NOLIMIT OFFBEAT IMPRESSIONS Women's Printed Embroidery T-Shirt (Cream)",
    brand: 'NOLIMIT OFFBEAT IMPRESSIONS',
    categoryId: 'women',
    subCategoryId: 'casual-wear',
    price: 2790,
    photoId: FashionPhotos.womanCasual2,
    catalogImageUrl: 'assets/images/nolimit_offbeat_womens_printed_embroidery_tee_cream.jpg',
    retailerUrl: kNolimit,
    description: 'Crew tee — cream with subtle embroidery / print detail.',
  ),

  // ─── WOMEN · Saree (bundled NOLIMIT heroes — same shots as nolimit.lk `_next/image` CDN) ──
  sampleProduct(
    id: 'nolimit-womens-pattu-saree-green-gold-alt',
    name: "Women's Pattu Saree (Green & Gold)",
    brand: 'NOLIMIT',
    categoryId: 'women',
    subCategoryId: 'saree',
    price: 45990,
    photoId: FashionPhotos.womanDress1,
    assetImage: 'assets/images/catalog_saree/pattu_green_gold.jpg',
    retailerUrl: r"https://www.nolimit.lk/products/Women's-Pattu-Saree-Green-&-Gold/66700",
    isFeatured: true,
    description: 'Pattu silk — green & gold zari.',
  ),
  sampleProduct(
    id: 'nolimit-womens-georgette-saree-assorted-19',
    name: "Women's Georgette Saree (Assorted)",
    brand: 'NOLIMIT',
    categoryId: 'women',
    subCategoryId: 'saree',
    price: 12990,
    photoId: FashionPhotos.womanDress1,
    assetImage: 'assets/images/catalog_saree/georgette_assorted_19.jpg',
    retailerUrl: kNolimit,
    description: 'Light georgette — assorted prints.',
  ),
  sampleProduct(
    id: 'nolimit-womens-silk-saree-assorted-16',
    name: "Women's Silk Saree (Assorted)",
    brand: 'NOLIMIT',
    categoryId: 'women',
    subCategoryId: 'saree',
    price: 16990,
    photoId: FashionPhotos.womanFormal3,
    assetImage: 'assets/images/catalog_saree/silk_assorted_16.jpg',
    retailerUrl: kNolimit,
  ),
  sampleProduct(
    id: 'nolimit-womens-batik-cotton-saree-13',
    name: "Women's Batik Cotton Saree (Assorted)",
    brand: 'NOLIMIT',
    categoryId: 'women',
    subCategoryId: 'saree',
    price: 9490,
    photoId: FashionPhotos.womanCasual2,
    assetImage: 'assets/images/catalog_saree/batik_13.jpg',
    retailerUrl: kNolimit,
  ),
  sampleProduct(
    id: 'nolimit-womens-batik-cotton-saree-6',
    name: "Women's Batik Cotton Saree (Assorted)",
    brand: 'NOLIMIT',
    categoryId: 'women',
    subCategoryId: 'saree',
    price: 8990,
    photoId: FashionPhotos.womanCasual2,
    assetImage: 'assets/images/catalog_saree/batik_6.jpg',
    retailerUrl: kNolimit,
  ),

  // ─── KIDS · Boys ─────────────────────────────────────────────────────────
  sampleProduct(
    id: 'nolimit-urbanwear-kids-boys-oversized-crew-tee-brown',
    name: 'NOLIMIT URBAN WEAR Kids Boys Crew Neck Short Sleeve Oversized T-Shirt (Brown)',
    brand: 'NOLIMIT URBAN WEAR',
    categoryId: 'children',
    subCategoryId: 'boys',
    price: 2490,
    photoId: FashionPhotos.kidsGroup1,
    catalogImageUrl: KidsBoysCatalogImageUrls.list[0],
    retailerUrl: kNolimit,
    description: 'Waffle-texture oversized crew tee — brown, 2–3 YRS style line.',
    isFeatured: true,
  ),
  sampleProduct(
    id: 'nolimit-urbanwear-boys-cuban-collar-shirt-black',
    name: 'NOLIMIT URBAN WEAR Boys Cuban Collar Oversized Casual Shirt (Black)',
    brand: 'NOLIMIT URBAN WEAR',
    categoryId: 'children',
    subCategoryId: 'boys',
    price: 2790,
    photoId: FashionPhotos.kidsGroup1,
    // Bundled — same NOLIMIT greencloudpos hero; avoids CDN fallback to the green placeholder tile.
    catalogImageUrl: 'assets/images/nolimit_urbanwear_boys_cuban_collar_shirt_black.jpg',
    retailerUrl: kNolimit,
    description: 'Oversized Cuban collar shirt — black & white stripe pattern, relaxed fit.',
  ),

  // ─── KIDS · Girls ────────────────────────────────────────────────────────
  sampleProduct(
    id: 'nolimit-daydream-drip-girls-oversized-tee-gray',
    name: 'NOLIMIT DAYDREAM DRIP Girls Oversized T-Shirt (Gray)',
    brand: 'NOLIMIT',
    categoryId: 'children',
    subCategoryId: 'girls',
    price: 2790,
    photoId: FashionPhotos.kidsPlay2,
    catalogImageUrl: 'assets/images/nolimit_daydream_drip_girls_oversized_tee_gray.jpg',
    retailerUrl: kNolimit,
    description: 'Oversized crew tee — light gray, sleeve stripe detail. DAYDREAM DRIP line.',
  ),
  sampleProduct(
    id: 'nolimit-lollilush-girls-stripe-dress-pink',
    name: 'NOLIMIT LOLLILUSH Girls Stripe Dress (Pink)',
    brand: 'NOLIMIT',
    categoryId: 'children',
    subCategoryId: 'girls',
    price: 2990,
    photoId: FashionPhotos.womanDress1,
    catalogImageUrl: 'assets/images/nolimit_lollilush_girls_stripe_dress_pink.jpg',
    retailerUrl: kNolimit,
    description: 'Tiered stripe dress — pink & white. LOLLILUSH line.',
    isFeatured: true,
  ),

  // ─── ACCESSORIES · Jewelry ─────────────────────────────────────────────────
  // (Legacy Pepper St. / ODEL jewellery samples removed.)

  // ─── ACCESSORIES · Bags ────────────────────────────────────────────────────
  sampleProduct(
    id: 'signature-leather-tote',
    name: 'Structured Leather Tote',
    brand: 'Signature',
    categoryId: 'accessories',
    subCategoryId: 'bags',
    price: 8990,
    photoId: FashionPhotos.handbag1,
    retailerUrl: kSignature,
    assetImage: 'assets/images/search_recent_tote.png',
  ),
  sampleProduct(
    id: 'nolimit-crossbody',
    name: 'Crossbody Bag',
    brand: 'NOLIMIT',
    categoryId: 'accessories',
    subCategoryId: 'bags',
    price: 4990,
    photoId: FashionPhotos.handbag1,
    retailerUrl: kNolimit,
    assetImage: 'assets/images/search_recent_tote.png',
  ),

  // ─── ACCESSORIES · Watches ───────────────────────────────────────────────
  sampleProduct(
    id: 'nolimit-sport-watch',
    name: 'Digital Sport Watch',
    brand: 'NOLIMIT',
    categoryId: 'accessories',
    subCategoryId: 'watches',
    price: 5490,
    photoId: FashionPhotos.watchClose,
    retailerUrl: kNolimit,
  ),

  // ─── ACCESSORIES · Belts ───────────────────────────────────────────────────
  sampleProduct(
    id: 'nolimit-reversible-belt',
    name: 'Reversible Belt',
    brand: 'NOLIMIT',
    categoryId: 'accessories',
    subCategoryId: 'belts',
    price: 2490,
    photoId: FashionPhotos.watchClose,
    catalogImageUrl: MenAccessoriesCatalogImageUrls.list[4],
    retailerUrl: kNolimit,
  ),

  ...kCatalogueExtensionProducts,
];
