// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwpzq46XYJPPIPrIRE412Nwr7lC0p0ET4',
    appId: '1:881203549474:web:3e273436700000e667c17b',
    messagingSenderId: '881203549474',
    projectId: 'fashion-store-app-2ac1f',
    authDomain: 'fashion-store-app-2ac1f.firebaseapp.com',
    storageBucket: 'fashion-store-app-2ac1f.firebasestorage.app',
    measurementId: 'G-GKHKESJT5Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6fE7KK0oEgwfKOFWgPTOZJ0aZ6aOUibw',
    appId: '1:881203549474:android:52546e32c834082767c17b',
    messagingSenderId: '881203549474',
    projectId: 'fashion-store-app-2ac1f',
    authDomain: 'fashion-store-app-2ac1f.firebaseapp.com',
    storageBucket: 'fashion-store-app-2ac1f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcocPcmEa7dXldNA-wRdBuY7kFhQzS1yY',
    appId: '1:881203549474:ios:fd84d37a4ffe995467c17b',
    messagingSenderId: '881203549474',
    projectId: 'fashion-store-app-2ac1f',
    authDomain: 'fashion-store-app-2ac1f.firebaseapp.com',
    storageBucket: 'fashion-store-app-2ac1f.firebasestorage.app',
    iosBundleId: 'com.example.atelier',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcocPcmEa7dXldNA-wRdBuY7kFhQzS1yY',
    appId: '1:881203549474:ios:fd84d37a4ffe995467c17b',
    messagingSenderId: '881203549474',
    projectId: 'fashion-store-app-2ac1f',
    authDomain: 'fashion-store-app-2ac1f.firebaseapp.com',
    storageBucket: 'fashion-store-app-2ac1f.firebasestorage.app',
    iosBundleId: 'com.example.atelier',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwpzq46XYJPPIPrIRE412Nwr7lC0p0ET4',
    appId: '1:881203549474:web:ec6064227b2807e367c17b',
    messagingSenderId: '881203549474',
    projectId: 'fashion-store-app-2ac1f',
    authDomain: 'fashion-store-app-2ac1f.firebaseapp.com',
    storageBucket: 'fashion-store-app-2ac1f.firebasestorage.app',
    measurementId: 'G-PN9YZWYFYG',
  );
}
